import { EquipmentType, type Exercise, MuscleGroup } from "@/backend";

const ex = (
  id: number,
  name: string,
  description: string,
  primaryMuscle: MuscleGroup,
  secondaryMuscles: MuscleGroup[],
  equipmentType: EquipmentType,
  cues: string,
  videoId: string,
): Exercise => ({
  id: BigInt(-id),
  name,
  description,
  primaryMuscle,
  secondaryMuscles,
  equipmentType,
  cues,
  isPlaceholder: false,
  videoUrl: `https://www.youtube.com/watch?v=${videoId}`,
  media: {
    imageUrls: [],
    videoUrls: [`https://www.youtube.com/watch?v=${videoId}`],
  },
});

const C = MuscleGroup.chest;
const BA = MuscleGroup.back;
const SH = MuscleGroup.shoulders;
const BI = MuscleGroup.biceps;
const TR = MuscleGroup.triceps;
const Q = MuscleGroup.quads;
const H = MuscleGroup.hamstrings;
const GL = MuscleGroup.glutes;
const CA = MuscleGroup.calves;
const CO = MuscleGroup.core;

const BW = EquipmentType.bodyweight;
const DB = EquipmentType.dumbbell;
const CB = EquipmentType.cable;
const MA = EquipmentType.machine;

export const staticExercises: Exercise[] = [
  // ── CHEST ──────────────────────────────────────────────────────────────────
  ex(
    1,
    "Barbell Bench Press",
    "The foundational compound chest press. Lowers a barbell to mid-chest and presses back to full extension.",
    C,
    [SH, TR],
    MA,
    "Retract scapulae, arch lower back slightly, drive feet into floor, lower bar to nipple line, press in a slight arc.",
    "vthMCtgUMGs",
  ),
  ex(
    2,
    "Incline Dumbbell Press",
    "Targets the upper chest by pressing dumbbells on a 30-45° incline bench.",
    C,
    [SH, TR],
    DB,
    "Set bench to 30-45°. Lower dumbbells to outer chest, elbows at 75°, press up and slightly inward at top.",
    "8iPEnn-ltC8",
  ),
  ex(
    3,
    "Cable Flye",
    "Isolation exercise that keeps constant tension on the pec fibers throughout the full arc of motion.",
    C,
    [SH],
    CB,
    "Stand between cables set at shoulder height. Slight elbow bend maintained. Bring hands together in a hugging motion, squeeze pecs at center.",
    "Iwe6AmxVf7o",
  ),
  ex(
    4,
    "Push-Up",
    "Classic bodyweight press that trains chest, shoulders, and triceps with core stabilization.",
    C,
    [SH, TR, CO],
    BW,
    "Hands shoulder-width, body in plank. Lower chest to within 1 inch of floor, elbows at ~45°. Full lockout at top.",
    "IODxDxX7oi4",
  ),
  ex(
    5,
    "Dumbbell Flye",
    "Isolation stretch movement targeting the pectoral muscle in a lengthened position.",
    C,
    [SH],
    DB,
    "Slight bend in elbows maintained throughout. Lower dumbbells in a wide arc until you feel a deep chest stretch, return by squeezing pecs.",
    "eozdVDA78K0",
  ),
  ex(
    6,
    "Decline Bench Press",
    "Emphasizes the lower sternal head of the pec with a slight negative decline angle.",
    C,
    [TR, SH],
    MA,
    "Set bench to -15 to -30°. Grip slightly wider than shoulder width. Lower bar to lower chest, press explosively.",
    "LfyQTbqc570",
  ),
  ex(
    7,
    "Chest Dip",
    "Bodyweight compound that strongly recruits lower chest when torso leans forward.",
    C,
    [TR, SH],
    BW,
    "Lean torso forward 30°. Lower until upper arms parallel to floor. Keep elbows flared slightly outward to emphasize chest over triceps.",
    "2z8JmcrW-As",
  ),
  ex(
    8,
    "Machine Chest Press",
    "Guided pressing movement ideal for muscle isolation and drop-sets without a spotter.",
    C,
    [SH, TR],
    MA,
    "Adjust seat so handles align with mid-chest. Press to full extension without locking elbows, return with control.",
    "xUm0BiZCWlQ",
  ),
  ex(
    9,
    "Pec Deck Flye",
    "Machine isolation that keeps constant resistance through entire range of motion.",
    C,
    [SH],
    MA,
    "Sit with arms on pads, elbows at shoulder height. Bring pads together, squeeze at peak contraction, release with control.",
    "Z57CtFmRMxA",
  ),
  ex(
    10,
    "Low-to-High Cable Flye",
    "Targets upper chest fibers by pulling cables upward from a low pulley attachment.",
    C,
    [SH],
    CB,
    "Set pulleys at lowest position. Press upward and inward in arc. Arms converge above chest. Feel stretch at bottom, peak contraction at top.",
    "FDdiaZulum98",
  ),
  ex(
    11,
    "Dumbbell Pullover",
    "Stretches the chest and lats simultaneously; builds thoracic expansion and pec length.",
    C,
    [BA, TR],
    DB,
    "Lie perpendicular on bench. Hold one dumbbell overhead with both hands. Lower behind head in arc, return by contracting chest and lats.",
    "FK4rHfqE5OY",
  ),
  ex(
    12,
    "Landmine Press",
    "Unilateral pressing movement that reduces shoulder impingement risk while building upper chest.",
    C,
    [SH, TR],
    MA,
    "Stand in athletic stance. Press barbell end upward and forward, rotating torso slightly. Alternate arms or use both.",
    "FwEtfCRbgJQ",
  ),

  // ── BACK ───────────────────────────────────────────────────────────────────
  ex(
    13,
    "Pull-Up",
    "The gold-standard back exercise for building lat width, scapular strength, and grip.",
    BA,
    [BI, CO],
    BW,
    "Dead hang start. Depress and retract scapulae first. Pull elbows down and back. Chin clears bar, lower with control.",
    "eGo4IYlbE5g",
  ),
  ex(
    14,
    "Barbell Row",
    "Heavy compound rowing movement that builds overall back thickness and strength.",
    BA,
    [BI, SH, CO],
    MA,
    "Hip hinge to ~45°. Grip outside shoulder width. Pull bar to lower ribcage, leading with elbows. Lower with control.",
    "FWJR5Ve8bnQ",
  ),
  ex(
    15,
    "Lat Pulldown",
    "Machine/cable version of the pull-up, excellent for beginners building pull-up strength.",
    BA,
    [BI, SH],
    MA,
    "Wide grip. Lean back 15°. Pull bar to upper chest, drive elbows down and back. Feel lat stretch at top.",
    "CAwf7n6Luuc",
  ),
  ex(
    16,
    "Seated Cable Row",
    "Horizontal pulling movement with constant cable tension; builds mid-back thickness.",
    BA,
    [BI, SH],
    CB,
    "Sit tall, slight knee bend. Pull handle to lower sternum, retract scapulae at end. Return until arms almost straight.",
    "GZbfZ033f74",
  ),
  ex(
    17,
    "Single-Arm Dumbbell Row",
    "Unilateral row allowing greater range of motion and reducing compensations.",
    BA,
    [BI],
    DB,
    "Brace on bench. Pull dumbbell to hip, keeping elbow close. Think 'elbow to hip' not 'hand to shoulder'. Full stretch at bottom.",
    "roCP4SeySwE",
  ),
  ex(
    18,
    "T-Bar Row",
    "Compound rowing with a close or wide grip that heavily loads the mid-back and traps.",
    BA,
    [BI, SH],
    MA,
    "Straddle bar, hip hinge, neutral or pronated grip. Pull to chest, squeeze at top, lower under control.",
    "j3Igk5nyZSc",
  ),
  ex(
    19,
    "Face Pull",
    "Cable exercise for rear delts and external rotators—critical for shoulder health.",
    BA,
    [SH],
    CB,
    "Set cable at face height. Pull rope to forehead, externally rotating hands outward at end range. Elbows flare high.",
    "rep-qVOkidg",
  ),
  ex(
    20,
    "Straight-Arm Pulldown",
    "Isolates the lat in the lengthened position while minimizing bicep involvement.",
    BA,
    [TR, CO],
    CB,
    "Stand at cable, slight forward lean. Arms straight with soft elbows. Pull bar to hips, squeezing lats at bottom.",
    "F3lTbWTcJxg",
  ),
  ex(
    21,
    "Deadlift",
    "The king of posterior chain exercises. Trains entire back, glutes, hamstrings, and traps.",
    BA,
    [GL, H, CO],
    MA,
    "Hinge at hips, neutral spine. Bar over mid-foot. Push floor away, keep bar against body. Lock out hips at top.",
    "op9kVnSso6Q",
  ),
  ex(
    22,
    "Chest-Supported Row",
    "Eliminates lower back stress by supporting the torso on an incline bench.",
    BA,
    [BI, SH],
    DB,
    "Lie prone on 45° incline bench. Row dumbbells to sides of torso, elbows at ~45° from body. Squeeze rhomboids.",
    "oNqHuZAaD18",
  ),
  ex(
    23,
    "Inverted Row",
    "Bodyweight horizontal pull—excellent for building row strength and scapular control.",
    BA,
    [BI, CO],
    BW,
    "Hang under bar at waist height. Body rigid in plank. Pull chest to bar, retract scapulae at top, lower slowly.",
    "LK3RQQj6R00",
  ),
  ex(
    24,
    "Shrug",
    "Isolates the upper trapezius for thickness and neck-to-shoulder development.",
    BA,
    [SH],
    DB,
    "Hold dumbbells at sides. Elevate shoulders straight up toward ears. Hold 1 second at top. No rolling—straight up, straight down.",
    "cJRJLFxHMwc",
  ),

  // ── SHOULDERS ──────────────────────────────────────────────────────────────
  ex(
    25,
    "Overhead Press",
    "Primary compound press for building shoulder mass and pressing strength.",
    SH,
    [TR, C],
    MA,
    "Grip just outside shoulder width. Bar at clavicle. Press overhead, lean through when bar passes forehead. Full lockout.",
    "2yjwXTZbDXo",
  ),
  ex(
    26,
    "Dumbbell Lateral Raise",
    "Isolation for the medial (side) deltoid—creates shoulder width and capped appearance.",
    SH,
    [],
    DB,
    "Slight forward lean. Lead with elbows, raise to ear height. Pinky slightly higher than thumb. Lower slowly in 3 seconds.",
    "3VcKaXpzqRo",
  ),
  ex(
    27,
    "Arnold Press",
    "Full-range dumbbell press with rotation that recruits all three deltoid heads.",
    SH,
    [TR],
    DB,
    "Start with palms facing you at shoulder height. Rotate palms outward as you press overhead. Reverse on the way down.",
    "6Z15_WdXmVw",
  ),
  ex(
    28,
    "Cable Lateral Raise",
    "Cable version of lateral raise maintaining tension at the bottom of the range.",
    SH,
    [],
    CB,
    "Stand beside cable, low pulley. Pull handle across body and up to ear height. Keep elbow slightly bent.",
    "PPTMowhNrico",
  ),
  ex(
    29,
    "Rear Delt Flye",
    "Targets the posterior deltoid—critical for rounded shoulder appearance and posture.",
    SH,
    [BA],
    DB,
    "Hinge to 45-90°. Arms hanging. Raise dumbbells outward to shoulder height, elbows soft. Squeeze rear delts at top.",
    "EA7u4Q_8HQ0",
  ),
  ex(
    30,
    "Upright Row",
    "Trains lateral and front delts plus upper traps with a vertical pulling motion.",
    SH,
    [BA, BI],
    DB,
    "Grip narrow. Pull bar or dumbbells straight up along body to chin. Elbows lead and flare above wrists.",
    "VjdtAT4MaRS",
  ),
  ex(
    31,
    "Front Raise",
    "Isolates the anterior deltoid with a forward elevation motion.",
    SH,
    [C],
    DB,
    "Neutral or pronated grip. Raise one or both arms to eye level. Control the descent.",
    "sOcu6EFKsEE",
  ),
  ex(
    32,
    "Seated Dumbbell Press",
    "Controlled overhead pressing in a seated position for deltoid hypertrophy.",
    SH,
    [TR, C],
    DB,
    "Back supported. Dumbbells at ear level, elbows at 90°. Press overhead to near-touch, lower with control.",
    "qEwKCR5JCog",
  ),
  ex(
    33,
    "Machine Shoulder Press",
    "Guided overhead press for hypertrophy, reduces stabilizer demand.",
    SH,
    [TR],
    MA,
    "Adjust seat so handles are at shoulder level. Press to full extension, lower to starting position with control.",
    "WvLMauqrnZ8",
  ),
  ex(
    34,
    "Cable Front Raise",
    "Front raise with cable for constant tension throughout the lift.",
    SH,
    [C],
    CB,
    "Low pulley, face away from stack. Raise straight arm to eye level. Control descent against cable resistance.",
    "iekj5EHaxmk",
  ),
  ex(
    35,
    "Band Pull-Apart",
    "Activates rear delts and external rotators; excellent as warm-up or accessory.",
    SH,
    [BA],
    BW,
    "Hold band at chest width, arms straight. Pull apart to shoulder width, squeezing rear delts. Return slowly.",
    "gJtGZBOCJFY",
  ),
  ex(
    36,
    "Push Press",
    "Explosive overhead press using a leg drive dip—bridges strength and power development.",
    SH,
    [TR, Q],
    BW,
    "Dip knees slightly, then drive hips up and press bar overhead. Use momentum to drive bar past sticking point.",
    "iaBVBup-ZnA",
  ),

  // ── BICEPS ─────────────────────────────────────────────────────────────────
  ex(
    37,
    "Barbell Curl",
    "Classic bicep mass builder with a supinated grip and full range of motion.",
    BI,
    [SH],
    MA,
    "Elbows at sides, no swinging. Curl bar to chin level, squeeze at top. Lower in 3 seconds, full extension at bottom.",
    "kwG2ipFRgfo",
  ),
  ex(
    38,
    "Dumbbell Hammer Curl",
    "Neutral grip curl targeting the brachialis and brachioradialis for arm thickness.",
    BI,
    [],
    DB,
    "Neutral (hammer) grip. Curl dumbbell toward shoulder without rotating. Squeeze at top, controlled descent.",
    "TwD-YGVP4Bk",
  ),
  ex(
    39,
    "Incline Dumbbell Curl",
    "Stretches the long head of the bicep in the lengthened position for better peak development.",
    BI,
    [SH],
    DB,
    "Set bench to 45-60°. Arms hang behind torso. Curl up without moving upper arm, full extension each rep.",
    "soxrZlIl35U",
  ),
  ex(
    40,
    "Cable Curl",
    "Maintains constant tension through the entire curl range using a low pulley cable.",
    BI,
    [SH],
    CB,
    "Stand at cable, EZ bar or straight bar attachment. Curl to chin level. Resist the cable on the way down.",
    "soxrZlIl35U",
  ),
  ex(
    41,
    "Preacher Curl",
    "Eliminates cheat-swinging and isolates the bicep at the bottom (stretched) position.",
    BI,
    [],
    MA,
    "Upper arm flat on pad. Curl fully to contraction, lower slowly to near-full extension. Don't hyperextend at bottom.",
    "fIWP-FRFNU0",
  ),
  ex(
    42,
    "Concentration Curl",
    "Single-arm isolation curl maximizing the mind-muscle connection and peak contraction.",
    BI,
    [],
    DB,
    "Seated, elbow braced on inner thigh. Curl dumbbell to shoulder, full extension at bottom. Squeeze hard at top.",
    "Jvj2wV0vOYU",
  ),
  ex(
    43,
    "EZ-Bar Curl",
    "Angled grip reduces wrist strain while still building significant bicep mass.",
    BI,
    [SH],
    MA,
    "Use EZ bar outer or inner grip. Elbows tight. Curl to chin, lower slow. Focus on supination at top.",
    "zG2-9e3fc7E",
  ),
  ex(
    44,
    "Spider Curl",
    "Targets the short head (inner bicep) by positioning elbow in front of the body.",
    BI,
    [],
    DB,
    "Lie prone on incline bench. Arms straight down. Curl dumbbells up, keeping upper arms vertical. Lower slowly.",
    "oOFDBKlajxQ",
  ),
  ex(
    45,
    "Cross-Body Hammer Curl",
    "Targets the brachialis by curling across the body to the opposite shoulder.",
    BI,
    [],
    DB,
    "Alternate arms, curling across to opposite shoulder. Neutral grip. Full extension between reps.",
    "TwD-YGVP4Bk",
  ),
  ex(
    46,
    "Reverse Curl",
    "Pronated grip curl that challenges the brachioradialis and improves forearm strength.",
    BI,
    [],
    MA,
    "Overhand grip on bar. Curl to chin level, elbows stationary. Control descent. Keep wrists neutral.",
    "nMIbsyRCBMA",
  ),
  ex(
    47,
    "21s Curl",
    "Tri-phase curl method: 7 bottom half reps, 7 top half reps, 7 full reps—maximum metabolic stress.",
    BI,
    [],
    DB,
    "7 reps lower half (bottom to 90°), 7 reps upper half (90° to top), 7 full-range reps. No rest between phases.",
    "kwG2ipFRgfo",
  ),
  ex(
    48,
    "Drag Curl",
    "Keeps elbows behind the body throughout the movement, maximizing the long head stretch.",
    BI,
    [SH],
    DB,
    "Drag barbell or dumbbells up the torso, elbows tracking back behind body. Do not let elbows come forward.",
    "oUu3f-IGWTk",
  ),

  // ── TRICEPS ────────────────────────────────────────────────────────────────
  ex(
    49,
    "Close-Grip Bench Press",
    "Compound pressing movement that shifts focus from chest to triceps.",
    TR,
    [C, SH],
    MA,
    "Grip 8-12 inches apart. Elbows slightly tucked, not flared. Lower to sternum, press straight up.",
    "nEF0bv2Yi54",
  ),
  ex(
    50,
    "Tricep Pushdown",
    "Cable isolation for the lateral and medial tricep head using a rope or bar attachment.",
    TR,
    [],
    CB,
    "Elbows pinned at sides. Push down to full extension, squeeze at bottom. Controlled return to 90° elbow flexion.",
    "2-LAMcpzODU",
  ),
  ex(
    51,
    "Overhead Tricep Extension",
    "Stretches the long head of the tricep—the largest of the three heads.",
    TR,
    [],
    DB,
    "Hold one dumbbell overhead with both hands. Lower behind head until elbows are fully bent. Press to lockout.",
    "_gsUck-8INk",
  ),
  ex(
    52,
    "Skull Crusher",
    "Close-grip barbell or EZ-bar lowered to the forehead—intense long head isolation.",
    TR,
    [],
    MA,
    "Lie flat on bench. Lower bar to forehead by bending elbows only. Press to lockout, elbows stationary.",
    "d_KZxkY_0cM",
  ),
  ex(
    53,
    "Tricep Dip",
    "Bodyweight pressing movement with high tricep recruitment when torso stays upright.",
    TR,
    [C, SH],
    BW,
    "Hands on bars, torso upright. Lower until 90° elbow bend. Press to full lockout. Upright torso = more tricep.",
    "0326dy_-CzM",
  ),
  ex(
    54,
    "Rope Pushdown",
    "Rope attachment allows greater wrist extension and lateral spread at the bottom for full tricep contraction.",
    TR,
    [],
    CB,
    "At lockout, spread rope handles outward. Squeeze triceps hard. Slow return to starting position.",
    "vB5OHsJ3EME",
  ),
  ex(
    55,
    "Diamond Push-Up",
    "Bodyweight tricep push-up with hands in a triangle/diamond shape under the chest.",
    TR,
    [C, SH],
    BW,
    "Form diamond with thumbs and index fingers. Lower chest to hands, elbows flare back. Full lockout at top.",
    "J0DXDuKE_-c",
  ),
  ex(
    56,
    "Single-Arm Cable Pushdown",
    "Unilateral isolation to address size or strength imbalances between tricep heads.",
    TR,
    [],
    CB,
    "One arm at a time, elbow pinned to side. Extend fully, resist on way back. Same volume each arm.",
    "kiuVA0gs3EI",
  ),
  ex(
    57,
    "Tate Press",
    "Dumbbell exercise that places the tricep in a shortened contraction position for maximum squeeze.",
    TR,
    [],
    DB,
    "Lie on bench, dumbbells in front of chest. Bend elbows so dumbbells lower to chest, pointing elbows outward. Extend back up.",
    "Yrm-JJ9zzOQ",
  ),
  ex(
    58,
    "JM Press",
    "A hybrid close-grip press and skull crusher that overloads the entire tricep under heavy load.",
    TR,
    [C],
    MA,
    "Close grip. Lower bar toward nose/forehead while tucking elbows to a 45°. Press back to lockout.",
    "nEF0bv2Yi54",
  ),
  ex(
    59,
    "Tricep Kickback",
    "Isolation for the lateral and long heads in a shortened position; best performed with light weight.",
    TR,
    [],
    DB,
    "Hinge to 45°. Upper arm parallel to floor. Extend forearm back to full lockout, squeeze hard. Lower with control.",
    "6SS6K3lAwZ8",
  ),
  ex(
    60,
    "Cable Overhead Extension",
    "Long-head stretch isolation using a high pulley cable for constant tension.",
    TR,
    [],
    CB,
    "Face away from stack, cable at overhead. Lean slightly forward. Extend forearms forward to lockout. Return slowly.",
    "_gsUck-8INk",
  ),

  // ── QUADS ──────────────────────────────────────────────────────────────────
  ex(
    61,
    "Back Squat",
    "The foundational lower body compound. Trains quads, glutes, hamstrings, and core.",
    Q,
    [GL, H, CO],
    MA,
    "Bar on traps, chest tall. Break at hips and knees simultaneously. Knees track toes. Descend below parallel. Drive floor away.",
    "ultWZbUMPL8",
  ),
  ex(
    62,
    "Front Squat",
    "Quad-dominant squat variation with bar in front rack—reduces lower back stress.",
    Q,
    [CO, GL],
    MA,
    "Bar rests on front delts, elbows high. Knees drive forward over toes. Keep torso very upright. Full depth.",
    "m4ytaCJZDoE",
  ),
  ex(
    63,
    "Leg Press",
    "Machine-based quad press that allows heavy loading without spinal compression.",
    Q,
    [GL, H],
    MA,
    "Feet shoulder-width. Press to near-full extension, lower until 90° knee angle. Feet low = more quad. Feet high = more glute.",
    "IZxyjW7MPJQ",
  ),
  ex(
    64,
    "Hack Squat",
    "Machine squat placing the load behind the body—excellent for quad isolation.",
    Q,
    [GL],
    MA,
    "Feet shoulder-width on platform. Lower to 90° or deeper. Press through full foot. Keep lower back pressed to pad.",
    "0tn5K9NlCfo",
  ),
  ex(
    65,
    "Leg Extension",
    "Machine isolation for the quadriceps—best used as a finisher after compound work.",
    Q,
    [],
    MA,
    "Sit with pads on lower shins. Extend to full lockout, squeeze quads. Lower slowly in 3 seconds. Don't use momentum.",
    "YyvSfVjQeL0",
  ),
  ex(
    66,
    "Bulgarian Split Squat",
    "Unilateral squat that isolates each leg, corrects imbalances, and builds hip mobility.",
    Q,
    [GL, H],
    DB,
    "Rear foot elevated on bench. Drop straight down, front knee tracks foot. Most weight through front heel. Drive up with quad.",
    "2C-uNgKwPLE",
  ),
  ex(
    67,
    "Walking Lunge",
    "Dynamic unilateral movement training balance, quad strength, and hip flexor mobility.",
    Q,
    [GL, H],
    DB,
    "Step forward, lower rear knee to ~1 inch from floor. Push off front foot. Keep torso upright. Alternate legs continuously.",
    "L8fvypPrzzs",
  ),
  ex(
    68,
    "Step-Up",
    "Functional unilateral quad and glute movement using a box or bench.",
    Q,
    [GL],
    DB,
    "Step onto box, drive through heel of front foot. Bring trailing leg up, lower back with control. Same leg for all reps or alternate.",
    "dQqApCGd5Ss",
  ),
  ex(
    69,
    "Sissy Squat",
    "Intense quad isolation targeting the rectus femoris in the lengthened position.",
    Q,
    [],
    BW,
    "Lean back, knees drive forward toward floor. Lower until quads are parallel to shin. Return by driving through toes.",
    "yPdee5i5kUE",
  ),
  ex(
    70,
    "Goblet Squat",
    "Beginner-friendly squat pattern holding a dumbbell at chest—builds depth and posture.",
    Q,
    [GL, CO],
    DB,
    "Hold dumbbell at chest. Squat deep, elbows inside knees at bottom. Keep chest tall. Drive through full foot.",
    "MxsFDhcyFyE",
  ),
  ex(
    71,
    "Spanish Squat",
    "Band-assisted squat that pins the shin vertically for maximum quad recruitment with less knee stress.",
    Q,
    [],
    BW,
    "Loop band around a sturdy object and your lower back. Feet forward, shins vertical. Squat deeply, knees remain vertical.",
    "yPdee5i5kUE",
  ),
  ex(
    72,
    "Cyclist Squat",
    "Heels-elevated squat maximizing quad stretch and activation with minimal hip involvement.",
    Q,
    [],
    DB,
    "Elevate heels 2-3 inches on plates. Squat straight down, keeping shins forward. Emphasizes quad sweep.",
    "m4ytaCJZDoE",
  ),

  // ── HAMSTRINGS ─────────────────────────────────────────────────────────────
  ex(
    73,
    "Romanian Deadlift",
    "Hip-hinge that stretches and loads the hamstrings through their full length.",
    H,
    [GL, BA],
    DB,
    "Soft knee bend. Push hips back, lower bar along legs. Feel hamstring stretch at bottom. Drive hips forward to stand.",
    "JCXUYuzwNrM",
  ),
  ex(
    74,
    "Lying Leg Curl",
    "Machine isolation for the hamstrings in a prone position.",
    H,
    [],
    MA,
    "Lie face down. Curl heels toward glutes, squeeze at top. Lower in 3 seconds to near-full extension.",
    "Orxoeast-HU",
  ),
  ex(
    75,
    "Seated Leg Curl",
    "Targets the hamstring at a longer muscle length than the lying version—better for hypertrophy.",
    H,
    [],
    MA,
    "Adjust pad over lower calf. Curl down and back. Squeeze at full flexion. Long, controlled return.",
    "1Tq3QdYUuHs",
  ),
  ex(
    76,
    "Nordic Hamstring Curl",
    "Eccentric-dominant exercise for hamstring injury prevention and peak strength.",
    H,
    [],
    BW,
    "Kneel on mat, ankles anchored. Lower torso toward floor slowly, fighting gravity. Push up with hands at bottom if needed.",
    "d8Ya3HGwliE",
  ),
  ex(
    77,
    "Good Morning",
    "Hip-hinge with bar on back—develops hamstring strength in the lengthened position under load.",
    H,
    [GL, BA, CO],
    MA,
    "Bar on upper traps. Hinge at hips, spine neutral. Lower torso to near-parallel, drive hips forward to return.",
    "YA-h3n9L4YU",
  ),
  ex(
    78,
    "Stiff-Leg Deadlift",
    "Similar to RDL but with legs straighter—maximizes hamstring and lower back involvement.",
    H,
    [GL, BA],
    MA,
    "Minimal knee bend. Lower bar below knee cap, spine neutral. Feel deep stretch, return by driving hips.",
    "ap-uj-YzAKU",
  ),
  ex(
    79,
    "Glute-Ham Raise",
    "Compound posterior chain movement blending hip extension and knee flexion.",
    H,
    [GL],
    MA,
    "Use GHR machine. Lower torso by straightening knees. Reverse with hamstring curl motion.",
    "d8Ya3HGwliE",
  ),
  ex(
    80,
    "Single-Leg Deadlift",
    "Unilateral hip-hinge that challenges hamstring strength and balance simultaneously.",
    H,
    [GL, CO],
    DB,
    "Stand on one leg, slight bend in knee. Hinge forward, raise opposite leg behind. Return by driving heel down and hips forward.",
    "5r6NHnbOCHs",
  ),
  ex(
    81,
    "Kettlebell Swing",
    "Explosive hip-hinge developing hamstring and glute power with cardiovascular demand.",
    H,
    [GL, CO],
    DB,
    "Hike bell between legs. Drive hips forward explosively. Bell floats to shoulder height. Let hips absorb the downswing.",
    "YSxHyfAdjT0",
  ),
  ex(
    82,
    "Leg Curl Drop Set",
    "High-volume hamstring isolation using progressive weight drops for maximum fatigue.",
    H,
    [],
    MA,
    "Perform 3 sets back-to-back, reducing weight 20% each time without rest. Full range each rep.",
    "Orxoeast-HU",
  ),
  ex(
    83,
    "Cable Pull-Through",
    "Hip-hinge using a cable for constant tension through the hamstrings and glutes.",
    H,
    [GL, CO],
    CB,
    "Face away from stack, rope between legs. Hinge at hips, rope goes between legs. Drive hips forward to stand.",
    "pMGj_FBGb_k",
  ),
  ex(
    84,
    "Stability Ball Leg Curl",
    "Bodyweight hamstring curl using instability to engage more muscle fibers.",
    H,
    [GL, CO],
    BW,
    "Lie on back, heels on ball. Bridge up, curl ball toward glutes, extend back out. Keep hips elevated throughout.",
    "Orxoeast-HU",
  ),

  // ── GLUTES ─────────────────────────────────────────────────────────────────
  ex(
    85,
    "Hip Thrust",
    "The most effective exercise for targeting the gluteus maximus through full range.",
    GL,
    [H],
    MA,
    "Upper back on bench. Bar over hips (pad recommended). Drive through full foot. Squeeze glutes hard at lockout.",
    "SEdqd6Hv55g",
  ),
  ex(
    86,
    "Glute Bridge",
    "Bodyweight glute activation and strength movement—the foundation of posterior chain training.",
    GL,
    [H, CO],
    BW,
    "Lie on back, feet flat. Drive hips up, squeeze glutes at top. Lower without touching floor between reps.",
    "OUgsJ8-Vi0E",
  ),
  ex(
    87,
    "Cable Kickback",
    "Isolation for the glutes using a cable for constant resistance throughout the motion.",
    GL,
    [H],
    CB,
    "Face cable machine, strap on ankle. Kick leg back and up, squeezing glute at top. Slow controlled return.",
    "JZCGwHcyoWE",
  ),
  ex(
    88,
    "Sumo Deadlift",
    "Wide-stance deadlift placing more demand on glutes and adductors vs. conventional.",
    GL,
    [H, Q, BA],
    MA,
    "Feet wider than shoulders, toes pointed out. Drop hips, grip inside stance. Drive through floor, hips and knees together.",
    "1RNZW9bJF9o",
  ),
  ex(
    89,
    "Step-Up with Knee Drive",
    "Functional glute exercise adding a knee drive at the top for full hip extension.",
    GL,
    [Q, H],
    DB,
    "Step onto box, drive top knee up to hip height. Pause, lower with control. Works glutes through full range.",
    "dQqApCGd5Ss",
  ),
  ex(
    90,
    "Single-Leg Hip Thrust",
    "Unilateral hip thrust for maximum glute isolation and addressing bilateral strength imbalances.",
    GL,
    [H, CO],
    BW,
    "Upper back on bench, one foot planted, other leg extended. Drive single-leg hip thrust, full extension at top.",
    "SEdqd6Hv55g",
  ),
  ex(
    91,
    "Donkey Kick",
    "Bodyweight glute isolation on hands and knees, emphasizing hip extension range.",
    GL,
    [],
    BW,
    "On hands and knees. Keep knee bent at 90°. Drive heel toward ceiling, squeeze glute at top. Lower without touching floor.",
    "KwFtKWVHBNc",
  ),
  ex(
    92,
    "Frog Pump",
    "High-rep glute activation exercise—excellent for pre-activation before heavy compound work.",
    GL,
    [],
    BW,
    "Lie on back, soles of feet together in frog position. Drive hips up, squeeze glutes hard. High reps, 20-30.",
    "OUgsJ8-Vi0E",
  ),
  ex(
    93,
    "Romanian Split Squat",
    "Hip-hinge version of the Bulgarian split squat that targets the glutes more than the quads.",
    GL,
    [H, Q],
    DB,
    "Rear foot elevated. Lean torso forward 45° as you descend. Hip-hinge emphasis, front heel stays down.",
    "2C-uNgKwPLE",
  ),
  ex(
    94,
    "Lateral Band Walk",
    "Targets the gluteus medius—key for hip stability and knee alignment during all lower body work.",
    GL,
    [],
    BW,
    "Band around ankles. Slight squat position. Step laterally, keeping tension in band. Avoid swaying torso.",
    "YJXNC1W8vhY",
  ),
  ex(
    95,
    "Reverse Hyperextension",
    "Targets glutes and lower back via hip extension on a reverse hyper machine.",
    GL,
    [H, BA],
    MA,
    "Lie face down, hips at pad edge, legs hanging. Raise legs to horizontal by squeezing glutes. Lower with control.",
    "B98PuKpwGxE",
  ),
  ex(
    96,
    "Abductor Machine",
    "Isolation for the gluteus medius and minimus using a hip abduction machine.",
    GL,
    [],
    MA,
    "Sit with pads on outer thighs. Push legs outward against resistance. Slow controlled return to starting position.",
    "YJXNC1W8vhY",
  ),

  // ── CALVES ─────────────────────────────────────────────────────────────────
  ex(
    97,
    "Standing Calf Raise",
    "Primary mass builder for the gastrocnemius—the large, visible calf muscle.",
    CA,
    [],
    MA,
    "Full stretch at bottom—heel below platform. Drive up onto toes, hold 1 second. Lower slowly in 3 seconds. Full ROM.",
    "gwLzBv7rSGc",
  ),
  ex(
    98,
    "Seated Calf Raise",
    "Targets the soleus (deeper calf) since the knee is bent, which disengages the gastrocnemius.",
    CA,
    [],
    MA,
    "Sit with knees at 90°, pads on lower quads. Push down through ball of foot. Full stretch, full contraction.",
    "M6hnECbGE0c",
  ),
  ex(
    99,
    "Donkey Calf Raise",
    "Stretches the calf under load in the hip-hinge position for greater gastrocnemius activation.",
    CA,
    [],
    MA,
    "Bend at hips 90°, toes on platform edge. Full stretch at bottom, complete rise at top. Slow eccentric.",
    "gwLzBv7rSGc",
  ),
  ex(
    100,
    "Single-Leg Calf Raise",
    "Unilateral calf training doubles the load on each leg, corrects imbalances.",
    CA,
    [],
    BW,
    "Stand on one leg on step edge. Full heel drop, complete rise. Hold balance. Use wall for support if needed.",
    "gwLzBv7rSGc",
  ),
  ex(
    101,
    "Jump Rope",
    "Plyometric calf conditioning improving elasticity, coordination, and cardiovascular fitness.",
    CA,
    [],
    BW,
    "Land on balls of feet. Minimal ground contact time. Keep elbows at sides, wrists rotate the rope. 2-3 minute rounds.",
    "u3zgHI8QnqE",
  ),
  ex(
    102,
    "Leg Press Calf Raise",
    "Calf raise performed on the leg press, allowing heavy loading and a comfortable range.",
    CA,
    [],
    MA,
    "Set safety stops. Place toes on lower platform edge. Full stretch, complete rise. No bouncing at bottom.",
    "IZxyjW7MPJQ",
  ),
  ex(
    103,
    "Smith Machine Calf Raise",
    "Stable guided calf raise allowing heavy loading with secure balance.",
    CA,
    [],
    MA,
    "Place plates on floor for toes. Full ROM. Pause 2 seconds at top, 3 second lowering phase.",
    "gwLzBv7rSGc",
  ),
  ex(
    104,
    "Box Jump",
    "Plyometric movement developing explosive calf and lower body power.",
    CA,
    [Q, GL, H],
    BW,
    "Soft knee bend, swing arms back. Jump explosively, land softly on box with bent knees. Step down, don't jump down.",
    "52igYcG3uHE",
  ),
  ex(
    105,
    "Calf Raises on Stair Edge",
    "Convenient bodyweight calf raise using a staircase for a full stretch below neutral.",
    CA,
    [],
    BW,
    "Toes on stair edge, heels hanging. Full dorsiflexion at bottom, full plantarflexion at top. Slow, controlled.",
    "gwLzBv7rSGc",
  ),
  ex(
    106,
    "Tibialis Raise",
    "Dorsiflexion exercise for the tibialis anterior—reduces shin splints and balances calf development.",
    CA,
    [],
    BW,
    "Heels on plate or step, body upright. Raise toes toward shins as high as possible. Lower slowly. High reps.",
    "pnRzfOBH3FE",
  ),
  ex(
    107,
    "Banded Calf Raise",
    "Band provides accommodating resistance—harder at the top where the calf is strongest.",
    CA,
    [],
    BW,
    "Loop band over knee area and anchor to floor. Rise onto toes against band resistance. Full range.",
    "gwLzBv7rSGc",
  ),

  // ── CORE ───────────────────────────────────────────────────────────────────
  ex(
    108,
    "Plank",
    "Fundamental isometric core exercise building anti-extension stability and total midline strength.",
    CO,
    [SH, GL],
    BW,
    "Forearms and toes. Neutral spine—don't sag hips or pike up. Squeeze everything: glutes, quads, abs, lats. Breathe.",
    "pSHjTRCQxIw",
  ),
  ex(
    109,
    "Dead Bug",
    "Anti-extension core stability drill that teaches proper spinal bracing and limb control.",
    CO,
    [],
    BW,
    "Lie on back. Lower opposite arm and leg simultaneously, keeping lower back flat against floor. Return, alternate.",
    "g_BYB0R-4Ws",
  ),
  ex(
    110,
    "Ab Wheel Rollout",
    "One of the most demanding anti-extension core exercises for the entire rectus abdominis.",
    CO,
    [SH, BA],
    BW,
    "Kneel with wheel in hands. Roll out slowly, hips don't drop. Brace hard. Pull back by contracting abs and lats.",
    "9ElWJAFOSNE",
  ),
  ex(
    111,
    "Cable Crunch",
    "Weighted flexion exercise for the rectus abdominis—allows progressive overload unlike bodyweight crunches.",
    CO,
    [],
    CB,
    "Kneel at cable. Pull rope to either side of head. Round lower back and crunch elbows to knees. Don't pull with arms.",
    "2fbujeH3F0E",
  ),
  ex(
    112,
    "Hanging Leg Raise",
    "Hip flexion + core compression exercise building lower abs and grip strength.",
    CO,
    [H],
    BW,
    "Hang from bar. Brace abs. Raise legs to 90° or above with control. Lower slowly without swinging.",
    "hdng3vmIHQk",
  ),
  ex(
    113,
    "Russian Twist",
    "Rotational exercise building the obliques and transverse abdominis.",
    CO,
    [],
    BW,
    "Sit with feet elevated or flat. Lean back 45°. Rotate side to side, touching floor beside hips. Control momentum.",
    "JyyvIeNuRhI",
  ),
  ex(
    114,
    "Pallof Press",
    "Anti-rotation core stability exercise—resists rotational force from a cable or band.",
    CO,
    [],
    CB,
    "Stand perpendicular to cable. Hold at chest. Press out and hold. Resist rotation. Return. Brace hard throughout.",
    "AH_QZLm_0-s",
  ),
  ex(
    115,
    "V-Up",
    "Full-body crunch folding upper and lower body simultaneously—high difficulty core movement.",
    CO,
    [],
    BW,
    "Lie flat. Simultaneously raise legs and torso to form a V. Touch hands to feet at top. Lower with control.",
    "7UiB6KPaZbk",
  ),
  ex(
    116,
    "Dragon Flag",
    "Advanced core exercise using the whole body as a lever—full spinal and ab engagement.",
    CO,
    [BA, SH],
    BW,
    "Grip bench behind head. Raise entire body to vertical. Lower as one rigid unit, hovering above bench.",
    "pvz7k5gQnAA",
  ),
  ex(
    117,
    "Bicycle Crunch",
    "Dynamic rotational crunch engaging rectus abdominis and obliques simultaneously.",
    CO,
    [],
    BW,
    "Hands behind head. Bring opposite elbow to knee, fully extending other leg. Alternate in a cycling motion. No neck pulling.",
    "9FGilxCbdz8",
  ),
  ex(
    118,
    "L-Sit",
    "Isometric hold requiring exceptional hip flexor and core strength.",
    CO,
    [TR, SH],
    BW,
    "Hold on bars or floor. Lift legs to horizontal and hold. Compress abs hard. Point toes. Start with tuck position.",
    "IUZscSMOwgY",
  ),
  ex(
    119,
    "Side Plank",
    "Targets the lateral core—obliques and quadratus lumborum—essential for spinal stability.",
    CO,
    [GL, SH],
    BW,
    "Elbow or hand on floor, body in straight line. Stack feet or stagger. Hold, then repeat on other side.",
    "K2EUqoiqHYw",
  ),
  ex(
    120,
    "Hollow Body Hold",
    "Gymnastics-based core exercise pressing lower back to floor while extending limbs.",
    CO,
    [],
    BW,
    "Lower back pressed to floor. Arms overhead, legs extended and elevated. Hold without arching. Progress by lowering legs.",
    "LlDNef_Uat4",
  ),
];

export default staticExercises;
