/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DifficultyLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const MuscleGroup = IDL.Variant({
  'shoulders' : IDL.Null,
  'arms' : IDL.Null,
  'back' : IDL.Null,
  'core' : IDL.Null,
  'chest' : IDL.Null,
  'legs' : IDL.Null,
});
export const EquipmentType = IDL.Variant({
  'bodyweight' : IDL.Null,
  'cable' : IDL.Null,
  'barbell' : IDL.Null,
  'dumbbell' : IDL.Null,
  'bands' : IDL.Null,
  'machine' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'seoTitle' : IDL.Text,
  'modifiedAt' : Time,
  'published' : IDL.Bool,
  'createdAt' : Time,
  'author' : IDL.Text,
  'seoKeywords' : IDL.Vec(IDL.Text),
  'seoMetaDescription' : IDL.Text,
});
export const BreathworkPractice = IDL.Record({
  'id' : IDL.Nat,
  'difficultyLevel' : DifficultyLevel,
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'mindfulnessBenefits' : IDL.Text,
  'recommendedExerciseIds' : IDL.Vec(IDL.Nat),
  'techniqueDescription' : IDL.Text,
  'mediaUrl' : IDL.Text,
});
export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'difficultyLevel' : DifficultyLevel,
  'name' : IDL.Text,
  'equipmentType' : EquipmentType,
  'instructions' : IDL.Text,
  'mediaUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
  'benefits' : IDL.Text,
  'muscleGroup' : MuscleGroup,
});
export const MuscleGroupDetails = IDL.Record({
  'exerciseIds' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const MusicPreference = IDL.Variant({
  'on' : IDL.Null,
  'off' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'musicPreference' : MusicPreference,
});
export const Routine = IDL.Record({
  'breathworkPracticeIds' : IDL.Vec(IDL.Nat),
  'exerciseIds' : IDL.Vec(IDL.Nat),
  'userId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBreathworkPractice' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Text,
        IDL.Nat,
        DifficultyLevel,
      ],
      [],
      [],
    ),
  'addExercise' : IDL.Func(
      [
        IDL.Text,
        MuscleGroup,
        EquipmentType,
        DifficultyLevel,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addMuscleGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addToRoutine' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createRoutine' : IDL.Func([], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'deleteBreathworkPractice' : IDL.Func([IDL.Nat], [], []),
  'deleteExercise' : IDL.Func([IDL.Nat], [], []),
  'deleteMuscleGroup' : IDL.Func([IDL.Text], [], []),
  'deleteRoutine' : IDL.Func([], [], []),
  'editBlogPost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'editBreathworkPractice' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Text,
        IDL.Nat,
        DifficultyLevel,
      ],
      [],
      [],
    ),
  'editExercise' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        MuscleGroup,
        EquipmentType,
        DifficultyLevel,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'editMuscleGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllBreathworkPractices' : IDL.Func(
      [],
      [IDL.Vec(BreathworkPractice)],
      ['query'],
    ),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getAllMuscleGroups' : IDL.Func([], [IDL.Vec(MuscleGroupDetails)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMuscleGroupDetails' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'exercises' : IDL.Vec(Exercise),
            'muscleGroup' : MuscleGroupDetails,
          })
        ),
      ],
      ['query'],
    ),
  'getMuscleGroupExercises' : IDL.Func(
      [MuscleGroup],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getRoutine' : IDL.Func([IDL.Principal], [IDL.Opt(Routine)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishBlogPost' : IDL.Func([IDL.Nat], [], []),
  'removeFromRoutine' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unpublishBlogPost' : IDL.Func([IDL.Nat], [], []),
  'updateMusicPreference' : IDL.Func([MusicPreference], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DifficultyLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const MuscleGroup = IDL.Variant({
    'shoulders' : IDL.Null,
    'arms' : IDL.Null,
    'back' : IDL.Null,
    'core' : IDL.Null,
    'chest' : IDL.Null,
    'legs' : IDL.Null,
  });
  const EquipmentType = IDL.Variant({
    'bodyweight' : IDL.Null,
    'cable' : IDL.Null,
    'barbell' : IDL.Null,
    'dumbbell' : IDL.Null,
    'bands' : IDL.Null,
    'machine' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'seoTitle' : IDL.Text,
    'modifiedAt' : Time,
    'published' : IDL.Bool,
    'createdAt' : Time,
    'author' : IDL.Text,
    'seoKeywords' : IDL.Vec(IDL.Text),
    'seoMetaDescription' : IDL.Text,
  });
  const BreathworkPractice = IDL.Record({
    'id' : IDL.Nat,
    'difficultyLevel' : DifficultyLevel,
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'mindfulnessBenefits' : IDL.Text,
    'recommendedExerciseIds' : IDL.Vec(IDL.Nat),
    'techniqueDescription' : IDL.Text,
    'mediaUrl' : IDL.Text,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'difficultyLevel' : DifficultyLevel,
    'name' : IDL.Text,
    'equipmentType' : EquipmentType,
    'instructions' : IDL.Text,
    'mediaUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
    'benefits' : IDL.Text,
    'muscleGroup' : MuscleGroup,
  });
  const MuscleGroupDetails = IDL.Record({
    'exerciseIds' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const MusicPreference = IDL.Variant({ 'on' : IDL.Null, 'off' : IDL.Null });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'musicPreference' : MusicPreference,
  });
  const Routine = IDL.Record({
    'breathworkPracticeIds' : IDL.Vec(IDL.Nat),
    'exerciseIds' : IDL.Vec(IDL.Nat),
    'userId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBreathworkPractice' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Text,
          IDL.Nat,
          DifficultyLevel,
        ],
        [],
        [],
      ),
    'addExercise' : IDL.Func(
        [
          IDL.Text,
          MuscleGroup,
          EquipmentType,
          DifficultyLevel,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addMuscleGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addToRoutine' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createRoutine' : IDL.Func([], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'deleteBreathworkPractice' : IDL.Func([IDL.Nat], [], []),
    'deleteExercise' : IDL.Func([IDL.Nat], [], []),
    'deleteMuscleGroup' : IDL.Func([IDL.Text], [], []),
    'deleteRoutine' : IDL.Func([], [], []),
    'editBlogPost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'editBreathworkPractice' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Text,
          IDL.Nat,
          DifficultyLevel,
        ],
        [],
        [],
      ),
    'editExercise' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          MuscleGroup,
          EquipmentType,
          DifficultyLevel,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'editMuscleGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllBreathworkPractices' : IDL.Func(
        [],
        [IDL.Vec(BreathworkPractice)],
        ['query'],
      ),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getAllMuscleGroups' : IDL.Func(
        [],
        [IDL.Vec(MuscleGroupDetails)],
        ['query'],
      ),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMuscleGroupDetails' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'exercises' : IDL.Vec(Exercise),
              'muscleGroup' : MuscleGroupDetails,
            })
          ),
        ],
        ['query'],
      ),
    'getMuscleGroupExercises' : IDL.Func(
        [MuscleGroup],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getRoutine' : IDL.Func([IDL.Principal], [IDL.Opt(Routine)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishBlogPost' : IDL.Func([IDL.Nat], [], []),
    'removeFromRoutine' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unpublishBlogPost' : IDL.Func([IDL.Nat], [], []),
    'updateMusicPreference' : IDL.Func([MusicPreference], [], []),
  });
};

export const init = ({ IDL }) => { return []; };