/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'seoTitle' : string,
  'modifiedAt' : Time,
  'published' : boolean,
  'createdAt' : Time,
  'author' : string,
  'seoKeywords' : Array<string>,
  'seoMetaDescription' : string,
}
export interface BreathworkPractice {
  'id' : bigint,
  'difficultyLevel' : DifficultyLevel,
  'duration' : bigint,
  'name' : string,
  'mindfulnessBenefits' : string,
  'recommendedExerciseIds' : Array<bigint>,
  'techniqueDescription' : string,
  'mediaUrl' : string,
}
export type DifficultyLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export type EquipmentType = { 'bodyweight' : null } |
  { 'cable' : null } |
  { 'barbell' : null } |
  { 'dumbbell' : null } |
  { 'bands' : null } |
  { 'machine' : null };
export interface Exercise {
  'id' : bigint,
  'difficultyLevel' : DifficultyLevel,
  'name' : string,
  'equipmentType' : EquipmentType,
  'instructions' : string,
  'mediaUrl' : string,
  'imageUrl' : string,
  'benefits' : string,
  'muscleGroup' : MuscleGroup,
}
export type MuscleGroup = { 'shoulders' : null } |
  { 'arms' : null } |
  { 'back' : null } |
  { 'core' : null } |
  { 'chest' : null } |
  { 'legs' : null };
export interface MuscleGroupDetails {
  'exerciseIds' : Array<bigint>,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
}
export type MusicPreference = { 'on' : null } |
  { 'off' : null };
export interface Routine {
  'breathworkPracticeIds' : Array<bigint>,
  'exerciseIds' : Array<bigint>,
  'userId' : Principal,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'musicPreference' : MusicPreference,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBreathworkPractice' : ActorMethod<
    [string, string, string, Array<bigint>, string, bigint, DifficultyLevel],
    undefined
  >,
  'addExercise' : ActorMethod<
    [
      string,
      MuscleGroup,
      EquipmentType,
      DifficultyLevel,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'addMuscleGroup' : ActorMethod<[string, string, string], undefined>,
  'addToRoutine' : ActorMethod<[bigint, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<
    [string, string, string, string, string, Array<string>],
    bigint
  >,
  'createRoutine' : ActorMethod<[], undefined>,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deleteBreathworkPractice' : ActorMethod<[bigint], undefined>,
  'deleteExercise' : ActorMethod<[bigint], undefined>,
  'deleteMuscleGroup' : ActorMethod<[string], undefined>,
  'deleteRoutine' : ActorMethod<[], undefined>,
  'editBlogPost' : ActorMethod<
    [bigint, string, string, string, string, string, Array<string>],
    undefined
  >,
  'editBreathworkPractice' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      Array<bigint>,
      string,
      bigint,
      DifficultyLevel,
    ],
    undefined
  >,
  'editExercise' : ActorMethod<
    [
      bigint,
      string,
      MuscleGroup,
      EquipmentType,
      DifficultyLevel,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'editMuscleGroup' : ActorMethod<[string, string, string], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllBreathworkPractices' : ActorMethod<[], Array<BreathworkPractice>>,
  'getAllExercises' : ActorMethod<[], Array<Exercise>>,
  'getAllMuscleGroups' : ActorMethod<[], Array<MuscleGroupDetails>>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMuscleGroupDetails' : ActorMethod<
    [string],
    [] | [{ 'exercises' : Array<Exercise>, 'muscleGroup' : MuscleGroupDetails }]
  >,
  'getMuscleGroupExercises' : ActorMethod<[MuscleGroup], Array<Exercise>>,
  'getRoutine' : ActorMethod<[Principal], [] | [Routine]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishBlogPost' : ActorMethod<[bigint], undefined>,
  'removeFromRoutine' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unpublishBlogPost' : ActorMethod<[bigint], undefined>,
  'updateMusicPreference' : ActorMethod<[MusicPreference], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];