/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MuscleGroup = IDL.Variant({
  'triceps' : IDL.Null,
  'shoulders' : IDL.Null,
  'back' : IDL.Null,
  'core' : IDL.Null,
  'chest' : IDL.Null,
  'quads' : IDL.Null,
  'hamstrings' : IDL.Null,
  'glutes' : IDL.Null,
  'calves' : IDL.Null,
  'biceps' : IDL.Null,
});
export const EquipmentType = IDL.Variant({
  'bodyweight' : IDL.Null,
  'cable' : IDL.Null,
  'dumbbell' : IDL.Null,
  'machine' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AmazonProduct = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'affiliateLink' : IDL.Text,
});
export const Time = IDL.Int;
export const BlogPostPreview = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'seoTitle' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Text,
  'memberOnly' : IDL.Bool,
  'seoMetaDescription' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'seoTitle' : IDL.Text,
  'modifiedAt' : Time,
  'published' : IDL.Bool,
  'createdAt' : Time,
  'author' : IDL.Text,
  'seoKeywords' : IDL.Vec(IDL.Text),
  'memberOnly' : IDL.Bool,
  'seoMetaDescription' : IDL.Text,
});
export const ExercisePreview = IDL.Record({
  'id' : IDL.Nat,
  'primaryMuscle' : MuscleGroup,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'primaryMuscle' : MuscleGroup,
  'cues' : IDL.Text,
  'name' : IDL.Text,
  'equipmentType' : EquipmentType,
  'imageUrl' : IDL.Text,
  'isPlaceholder' : IDL.Bool,
  'videoUrl' : IDL.Text,
  'secondaryMuscles' : IDL.Vec(MuscleGroup),
});
export const Membership = IDL.Record({
  'principal' : IDL.Principal,
  'active' : IDL.Bool,
  'stripeId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'membershipStatus' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MuscleGroupCard = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'heroImage' : IDL.Opt(ExternalBlob),
  'imageUrl' : IDL.Text,
});
export const MuscleGroupDetails = IDL.Record({
  'exerciseIds' : IDL.Vec(IDL.Nat),
  'card' : MuscleGroupCard,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAmazonProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addExercise' : IDL.Func(
      [
        IDL.Text,
        MuscleGroup,
        IDL.Vec(MuscleGroup),
        EquipmentType,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'addMembership' : IDL.Func([IDL.Text], [], []),
  'addMembershipForUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteAmazonProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'deleteExercise' : IDL.Func([IDL.Nat], [], []),
  'getAffiliateDisclosure' : IDL.Func([], [IDL.Text], ['query']),
  'getAllAmazonProducts' : IDL.Func([], [IDL.Vec(AmazonProduct)], ['query']),
  'getAllBlogPostPreviews' : IDL.Func(
      [],
      [IDL.Vec(BlogPostPreview)],
      ['query'],
    ),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllExercisePreviews' : IDL.Func(
      [],
      [IDL.Vec(ExercisePreview)],
      ['query'],
    ),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getAllMemberships' : IDL.Func([], [IDL.Vec(Membership)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPostPreview' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(BlogPostPreview)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMembership' : IDL.Func([], [IDL.Opt(Membership)], ['query']),
  'getMuscleGroupArtist' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MuscleGroupCard)],
      ['query'],
    ),
  'getMuscleGroupArtists' : IDL.Func([], [IDL.Vec(MuscleGroupCard)], ['query']),
  'getMuscleGroupExercisePreviews' : IDL.Func(
      [MuscleGroup],
      [IDL.Vec(ExercisePreview)],
      ['query'],
    ),
  'getMuscleGroupExercises' : IDL.Func(
      [MuscleGroup],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getMuscleGroups' : IDL.Func([], [IDL.Vec(MuscleGroupDetails)], ['query']),
  'getPrivacyPolicy' : IDL.Func([], [IDL.Text], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasActiveMembership' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'publishBlogPost' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unpublishBlogPost' : IDL.Func([IDL.Nat], [], []),
  'updateAmazonProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateBlogPost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateExercise' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        MuscleGroup,
        IDL.Vec(MuscleGroup),
        EquipmentType,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateMembershipStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'updateMuscleGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateMuscleGroupArtist' : IDL.Func([IDL.Text, MuscleGroupCard], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MuscleGroup = IDL.Variant({
    'triceps' : IDL.Null,
    'shoulders' : IDL.Null,
    'back' : IDL.Null,
    'core' : IDL.Null,
    'chest' : IDL.Null,
    'quads' : IDL.Null,
    'hamstrings' : IDL.Null,
    'glutes' : IDL.Null,
    'calves' : IDL.Null,
    'biceps' : IDL.Null,
  });
  const EquipmentType = IDL.Variant({
    'bodyweight' : IDL.Null,
    'cable' : IDL.Null,
    'dumbbell' : IDL.Null,
    'machine' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AmazonProduct = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'affiliateLink' : IDL.Text,
  });
  const Time = IDL.Int;
  const BlogPostPreview = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'seoTitle' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Text,
    'memberOnly' : IDL.Bool,
    'seoMetaDescription' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'seoTitle' : IDL.Text,
    'modifiedAt' : Time,
    'published' : IDL.Bool,
    'createdAt' : Time,
    'author' : IDL.Text,
    'seoKeywords' : IDL.Vec(IDL.Text),
    'memberOnly' : IDL.Bool,
    'seoMetaDescription' : IDL.Text,
  });
  const ExercisePreview = IDL.Record({
    'id' : IDL.Nat,
    'primaryMuscle' : MuscleGroup,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'primaryMuscle' : MuscleGroup,
    'cues' : IDL.Text,
    'name' : IDL.Text,
    'equipmentType' : EquipmentType,
    'imageUrl' : IDL.Text,
    'isPlaceholder' : IDL.Bool,
    'videoUrl' : IDL.Text,
    'secondaryMuscles' : IDL.Vec(MuscleGroup),
  });
  const Membership = IDL.Record({
    'principal' : IDL.Principal,
    'active' : IDL.Bool,
    'stripeId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'membershipStatus' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MuscleGroupCard = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'heroImage' : IDL.Opt(ExternalBlob),
    'imageUrl' : IDL.Text,
  });
  const MuscleGroupDetails = IDL.Record({
    'exerciseIds' : IDL.Vec(IDL.Nat),
    'card' : MuscleGroupCard,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAmazonProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addExercise' : IDL.Func(
        [
          IDL.Text,
          MuscleGroup,
          IDL.Vec(MuscleGroup),
          EquipmentType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'addMembership' : IDL.Func([IDL.Text], [], []),
    'addMembershipForUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteAmazonProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'deleteExercise' : IDL.Func([IDL.Nat], [], []),
    'getAffiliateDisclosure' : IDL.Func([], [IDL.Text], ['query']),
    'getAllAmazonProducts' : IDL.Func([], [IDL.Vec(AmazonProduct)], ['query']),
    'getAllBlogPostPreviews' : IDL.Func(
        [],
        [IDL.Vec(BlogPostPreview)],
        ['query'],
      ),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllExercisePreviews' : IDL.Func(
        [],
        [IDL.Vec(ExercisePreview)],
        ['query'],
      ),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getAllMemberships' : IDL.Func([], [IDL.Vec(Membership)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPostPreview' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BlogPostPreview)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMembership' : IDL.Func([], [IDL.Opt(Membership)], ['query']),
    'getMuscleGroupArtist' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MuscleGroupCard)],
        ['query'],
      ),
    'getMuscleGroupArtists' : IDL.Func(
        [],
        [IDL.Vec(MuscleGroupCard)],
        ['query'],
      ),
    'getMuscleGroupExercisePreviews' : IDL.Func(
        [MuscleGroup],
        [IDL.Vec(ExercisePreview)],
        ['query'],
      ),
    'getMuscleGroupExercises' : IDL.Func(
        [MuscleGroup],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getMuscleGroups' : IDL.Func([], [IDL.Vec(MuscleGroupDetails)], ['query']),
    'getPrivacyPolicy' : IDL.Func([], [IDL.Text], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasActiveMembership' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'publishBlogPost' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unpublishBlogPost' : IDL.Func([IDL.Nat], [], []),
    'updateAmazonProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateBlogPost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateExercise' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          MuscleGroup,
          IDL.Vec(MuscleGroup),
          EquipmentType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateMembershipStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'updateMuscleGroup' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateMuscleGroupArtist' : IDL.Func([IDL.Text, MuscleGroupCard], [], []),
  });
};

export const init = ({ IDL }) => { return []; };