/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BlogMedia {
    imageUrls: Array<string>;
    videoUrls: Array<string>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface BlogPostPreview {
    id: bigint;
    title: string;
    seoTitle: string;
    createdAt: Time;
    author: string;
    memberOnly: boolean;
    seoMetaDescription: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface WorkoutRoutine {
    principal: Principal;
    name: string;
    exercises: Array<bigint>;
}
export interface AmazonProduct {
    id: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: string;
    affiliateLink: string;
}
export interface MuscleGroupDetails {
    exerciseIds: Array<bigint>;
    card: MuscleGroupCard;
    name: string;
    description: string;
    imageUrl: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface MuscleGroupCard {
    title: string;
    description: string;
    heroImage?: ExternalBlob;
    imageUrl: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface MiscConfig {
    adminContactEmail: string;
    supportContactEmail: string;
}
export interface ExercisePreview {
    id: bigint;
    primaryMuscle: MuscleGroup;
    name: string;
    imageUrl: string;
}
export interface Exercise {
    id: bigint;
    media: ExerciseMedia;
    primaryMuscle: MuscleGroup;
    cues: string;
    name: string;
    equipmentType: EquipmentType;
    description: string;
    isPlaceholder: boolean;
    videoUrl: string;
    secondaryMuscles: Array<MuscleGroup>;
}
export interface BlogPost {
    id: bigint;
    media: BlogMedia;
    title: string;
    content: string;
    seoTitle: string;
    modifiedAt: Time;
    published: boolean;
    createdAt: Time;
    author: string;
    seoKeywords: Array<string>;
    memberOnly: boolean;
    seoMetaDescription: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Membership {
    principal: Principal;
    active: boolean;
    price: bigint;
    stripeId: string;
}
export interface NutritionArticle {
    id: bigint;
    media: BlogMedia;
    title: string;
    content: string;
    published: boolean;
    createdAt: Time;
    author: string;
    memberOnly: boolean;
}
export interface ExerciseMedia {
    imageUrls: Array<string>;
    videoUrls: Array<string>;
}
export interface UserProfile {
    name: string;
    email?: string;
    membershipStatus?: string;
}
export interface NutritionArticlePreview {
    id: bigint;
    title: string;
    createdAt: Time;
    author: string;
    memberOnly: boolean;
}
export enum EquipmentType {
    bodyweight = "bodyweight",
    cable = "cable",
    dumbbell = "dumbbell",
    machine = "machine"
}
export enum MuscleGroup {
    triceps = "triceps",
    shoulders = "shoulders",
    back = "back",
    core = "core",
    chest = "chest",
    quads = "quads",
    hamstrings = "hamstrings",
    glutes = "glutes",
    calves = "calves",
    biceps = "biceps"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAmazonProduct(name: string, description: string, imageUrl: string, category: string, affiliateLink: string): Promise<void>;
    addExercise(name: string, description: string, primaryMuscle: MuscleGroup, secondaryMuscles: Array<MuscleGroup>, equipmentType: EquipmentType, videoUrl: string, cues: string, media: ExerciseMedia, isPlaceholder: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBlogPost(title: string, content: string, author: string, memberOnly: boolean, media: BlogMedia, seoTitle: string, seoMetaDescription: string, seoKeywords: Array<string>): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createNutritionArticle(title: string, content: string, author: string, media: BlogMedia, memberOnly: boolean): Promise<void>;
    createWorkoutRoutine(name: string, exerciseIds: Array<bigint>): Promise<void>;
    deleteAmazonProduct(id: bigint): Promise<void>;
    deleteBlogPost(id: bigint): Promise<void>;
    deleteExercise(id: bigint): Promise<void>;
    deleteNutritionArticle(id: bigint): Promise<void>;
    deleteWorkoutRoutine(name: string): Promise<void>;
    getAllAmazonProducts(): Promise<Array<AmazonProduct>>;
    getAllBlogPostsAdmin(): Promise<Array<BlogPost>>;
    getAllExercisePreviews(): Promise<Array<ExercisePreview>>;
    getAllExercises(): Promise<Array<Exercise>>;
    getAllExercisesAdmin(): Promise<Array<Exercise>>;
    getAllMuscleGroups(): Promise<Array<MuscleGroupDetails>>;
    getAllNutritionArticlesAdmin(): Promise<Array<NutritionArticle>>;
    getBlogPost(id: bigint): Promise<BlogPost | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerWorkoutRoutines(): Promise<Array<WorkoutRoutine>>;
    getExercise(id: bigint): Promise<Exercise | null>;
    getExercisesByMuscleGroup(muscleGroup: MuscleGroup): Promise<Array<Exercise>>;
    getMembership(user: Principal): Promise<Membership | null>;
    getMiscConfig(): Promise<MiscConfig | null>;
    getMuscleGroupDetails(name: string): Promise<MuscleGroupDetails | null>;
    getMyMembership(): Promise<Membership | null>;
    getNutritionArticle(id: bigint): Promise<NutritionArticle | null>;
    getPrivacyPolicy(): Promise<string>;
    getPublishedBlogPostPreviews(): Promise<Array<BlogPostPreview>>;
    getPublishedNutritionArticlePreviews(): Promise<Array<NutritionArticlePreview>>;
    getStripeConfig(): Promise<StripeConfiguration | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserWorkoutRoutines(user: Principal): Promise<Array<WorkoutRoutine>>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    publishBlogPost(id: bigint, published: boolean): Promise<void>;
    publishNutritionArticle(id: bigint, published: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setMembership(user: Principal, active: boolean, stripeId: string, price: bigint): Promise<void>;
    setMiscConfig(config: MiscConfig): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAmazonProduct(id: bigint, name: string, description: string, imageUrl: string, category: string, affiliateLink: string): Promise<void>;
    updateBlogPost(id: bigint, title: string, content: string, author: string, memberOnly: boolean, media: BlogMedia, seoTitle: string, seoMetaDescription: string, seoKeywords: Array<string>): Promise<void>;
    updateExercise(id: bigint, name: string, description: string, primaryMuscle: MuscleGroup, secondaryMuscles: Array<MuscleGroup>, equipmentType: EquipmentType, videoUrl: string, cues: string, media: ExerciseMedia, isPlaceholder: boolean): Promise<void>;
    updateMuscleGroupCard(name: string, card: MuscleGroupCard): Promise<void>;
    updateNutritionArticle(id: bigint, title: string, content: string, author: string, media: BlogMedia, memberOnly: boolean): Promise<void>;
    updateWorkoutRoutine(name: string, exerciseIds: Array<bigint>): Promise<void>;
}
import type { BlogPost as _BlogPost, EquipmentType as _EquipmentType, Exercise as _Exercise, ExerciseMedia as _ExerciseMedia, ExercisePreview as _ExercisePreview, ExternalBlob as _ExternalBlob, Membership as _Membership, MiscConfig as _MiscConfig, MuscleGroup as _MuscleGroup, MuscleGroupCard as _MuscleGroupCard, MuscleGroupDetails as _MuscleGroupDetails, NutritionArticle as _NutritionArticle, StripeConfiguration as _StripeConfiguration, StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAmazonProduct(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAmazonProduct(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAmazonProduct(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addExercise(arg0: string, arg1: string, arg2: MuscleGroup, arg3: Array<MuscleGroup>, arg4: EquipmentType, arg5: string, arg6: string, arg7: ExerciseMedia, arg8: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExercise(arg0, arg1, to_candid_MuscleGroup_n8(this._uploadFile, this._downloadFile, arg2), to_candid_vec_n10(this._uploadFile, this._downloadFile, arg3), to_candid_EquipmentType_n11(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExercise(arg0, arg1, to_candid_MuscleGroup_n8(this._uploadFile, this._downloadFile, arg2), to_candid_vec_n10(this._uploadFile, this._downloadFile, arg3), to_candid_EquipmentType_n11(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBlogPost(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: BlogMedia, arg5: string, arg6: string, arg7: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createNutritionArticle(arg0: string, arg1: string, arg2: string, arg3: BlogMedia, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNutritionArticle(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNutritionArticle(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createWorkoutRoutine(arg0: string, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkoutRoutine(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkoutRoutine(arg0, arg1);
            return result;
        }
    }
    async deleteAmazonProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAmazonProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAmazonProduct(arg0);
            return result;
        }
    }
    async deleteBlogPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteExercise(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExercise(arg0);
            return result;
        }
    }
    async deleteNutritionArticle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNutritionArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNutritionArticle(arg0);
            return result;
        }
    }
    async deleteWorkoutRoutine(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkoutRoutine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkoutRoutine(arg0);
            return result;
        }
    }
    async getAllAmazonProducts(): Promise<Array<AmazonProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAmazonProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAmazonProducts();
            return result;
        }
    }
    async getAllBlogPostsAdmin(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPostsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPostsAdmin();
            return result;
        }
    }
    async getAllExercisePreviews(): Promise<Array<ExercisePreview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercisePreviews();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercisePreviews();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercises();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercises();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExercisesAdmin(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercisesAdmin();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercisesAdmin();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMuscleGroups(): Promise<Array<MuscleGroupDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMuscleGroups();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMuscleGroups();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNutritionArticlesAdmin(): Promise<Array<NutritionArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNutritionArticlesAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNutritionArticlesAdmin();
            return result;
        }
    }
    async getBlogPost(arg0: bigint): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWorkoutRoutines(): Promise<Array<WorkoutRoutine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWorkoutRoutines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWorkoutRoutines();
            return result;
        }
    }
    async getExercise(arg0: bigint): Promise<Exercise | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercise(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercise(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExercisesByMuscleGroup(arg0: MuscleGroup): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercisesByMuscleGroup(to_candid_MuscleGroup_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercisesByMuscleGroup(to_candid_MuscleGroup_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembership(arg0: Principal): Promise<Membership | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembership(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembership(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMiscConfig(): Promise<MiscConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMiscConfig();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMiscConfig();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMuscleGroupDetails(arg0: string): Promise<MuscleGroupDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMuscleGroupDetails(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMuscleGroupDetails(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMembership(): Promise<Membership | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMembership();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMembership();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNutritionArticle(arg0: bigint): Promise<NutritionArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNutritionArticle(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNutritionArticle(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrivacyPolicy(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrivacyPolicy();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrivacyPolicy();
            return result;
        }
    }
    async getPublishedBlogPostPreviews(): Promise<Array<BlogPostPreview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedBlogPostPreviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedBlogPostPreviews();
            return result;
        }
    }
    async getPublishedNutritionArticlePreviews(): Promise<Array<NutritionArticlePreview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedNutritionArticlePreviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedNutritionArticlePreviews();
            return result;
        }
    }
    async getStripeConfig(): Promise<StripeConfiguration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeConfig();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeConfig();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWorkoutRoutines(arg0: Principal): Promise<Array<WorkoutRoutine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWorkoutRoutines(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWorkoutRoutines(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async publishBlogPost(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishBlogPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishBlogPost(arg0, arg1);
            return result;
        }
    }
    async publishNutritionArticle(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishNutritionArticle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishNutritionArticle(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setMembership(arg0: Principal, arg1: boolean, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMembership(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMembership(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setMiscConfig(arg0: MiscConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMiscConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMiscConfig(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAmazonProduct(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAmazonProduct(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAmazonProduct(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateBlogPost(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: boolean, arg5: BlogMedia, arg6: string, arg7: string, arg8: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateExercise(arg0: bigint, arg1: string, arg2: string, arg3: MuscleGroup, arg4: Array<MuscleGroup>, arg5: EquipmentType, arg6: string, arg7: string, arg8: ExerciseMedia, arg9: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExercise(arg0, arg1, arg2, to_candid_MuscleGroup_n8(this._uploadFile, this._downloadFile, arg3), to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), to_candid_EquipmentType_n11(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExercise(arg0, arg1, arg2, to_candid_MuscleGroup_n8(this._uploadFile, this._downloadFile, arg3), to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), to_candid_EquipmentType_n11(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async updateMuscleGroupCard(arg0: string, arg1: MuscleGroupCard): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMuscleGroupCard(arg0, await to_candid_MuscleGroupCard_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMuscleGroupCard(arg0, await to_candid_MuscleGroupCard_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateNutritionArticle(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: BlogMedia, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNutritionArticle(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNutritionArticle(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateWorkoutRoutine(arg0: string, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkoutRoutine(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkoutRoutine(arg0, arg1);
            return result;
        }
    }
}
function from_candid_EquipmentType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EquipmentType): EquipmentType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ExercisePreview_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExercisePreview): ExercisePreview {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Exercise_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_MuscleGroupCard_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MuscleGroupCard): Promise<MuscleGroupCard> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_MuscleGroupDetails_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MuscleGroupDetails): Promise<MuscleGroupDetails> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_MuscleGroup_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MuscleGroup): MuscleGroup {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Exercise]): Exercise | null {
    return value.length === 0 ? null : from_candid_Exercise_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Membership]): Membership | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MiscConfig]): MiscConfig | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MuscleGroupDetails]): Promise<MuscleGroupDetails | null> {
    return value.length === 0 ? null : await from_candid_MuscleGroupDetails_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NutritionArticle]): NutritionArticle | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StripeConfiguration]): StripeConfiguration | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    primaryMuscle: _MuscleGroup;
    name: string;
    imageUrl: string;
}): {
    id: bigint;
    primaryMuscle: MuscleGroup;
    name: string;
    imageUrl: string;
} {
    return {
        id: value.id,
        primaryMuscle: from_candid_MuscleGroup_n18(_uploadFile, _downloadFile, value.primaryMuscle),
        name: value.name,
        imageUrl: value.imageUrl
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    media: _ExerciseMedia;
    primaryMuscle: _MuscleGroup;
    cues: string;
    name: string;
    equipmentType: _EquipmentType;
    description: string;
    isPlaceholder: boolean;
    videoUrl: string;
    secondaryMuscles: Array<_MuscleGroup>;
}): {
    id: bigint;
    media: ExerciseMedia;
    primaryMuscle: MuscleGroup;
    cues: string;
    name: string;
    equipmentType: EquipmentType;
    description: string;
    isPlaceholder: boolean;
    videoUrl: string;
    secondaryMuscles: Array<MuscleGroup>;
} {
    return {
        id: value.id,
        media: value.media,
        primaryMuscle: from_candid_MuscleGroup_n18(_uploadFile, _downloadFile, value.primaryMuscle),
        cues: value.cues,
        name: value.name,
        equipmentType: from_candid_EquipmentType_n23(_uploadFile, _downloadFile, value.equipmentType),
        description: value.description,
        isPlaceholder: value.isPlaceholder,
        videoUrl: value.videoUrl,
        secondaryMuscles: from_candid_vec_n25(_uploadFile, _downloadFile, value.secondaryMuscles)
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exerciseIds: Array<bigint>;
    card: _MuscleGroupCard;
    name: string;
    description: string;
    imageUrl: string;
}): Promise<{
    exerciseIds: Array<bigint>;
    card: MuscleGroupCard;
    name: string;
    description: string;
    imageUrl: string;
}> {
    return {
        exerciseIds: value.exerciseIds,
        card: await from_candid_MuscleGroupCard_n29(_uploadFile, _downloadFile, value.card),
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    heroImage: [] | [_ExternalBlob];
    imageUrl: string;
}): Promise<{
    title: string;
    description: string;
    heroImage?: ExternalBlob;
    imageUrl: string;
}> {
    return {
        title: value.title,
        description: value.description,
        heroImage: record_opt_to_undefined(await from_candid_opt_n31(_uploadFile, _downloadFile, value.heroImage)),
        imageUrl: value.imageUrl
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    membershipStatus: [] | [string];
}): {
    name: string;
    email?: string;
    membershipStatus?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.email)),
        membershipStatus: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.membershipStatus))
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    triceps: null;
} | {
    shoulders: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    quads: null;
} | {
    hamstrings: null;
} | {
    glutes: null;
} | {
    calves: null;
} | {
    biceps: null;
}): MuscleGroup {
    return "triceps" in value ? MuscleGroup.triceps : "shoulders" in value ? MuscleGroup.shoulders : "back" in value ? MuscleGroup.back : "core" in value ? MuscleGroup.core : "chest" in value ? MuscleGroup.chest : "quads" in value ? MuscleGroup.quads : "hamstrings" in value ? MuscleGroup.hamstrings : "glutes" in value ? MuscleGroup.glutes : "calves" in value ? MuscleGroup.calves : "biceps" in value ? MuscleGroup.biceps : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bodyweight: null;
} | {
    cable: null;
} | {
    dumbbell: null;
} | {
    machine: null;
}): EquipmentType {
    return "bodyweight" in value ? EquipmentType.bodyweight : "cable" in value ? EquipmentType.cable : "dumbbell" in value ? EquipmentType.dumbbell : "machine" in value ? EquipmentType.machine : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n48(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExercisePreview>): Array<ExercisePreview> {
    return value.map((x)=>from_candid_ExercisePreview_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MuscleGroup>): Array<MuscleGroup> {
    return value.map((x)=>from_candid_MuscleGroup_n18(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MuscleGroupDetails>): Promise<Array<MuscleGroupDetails>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MuscleGroupDetails_n27(_uploadFile, _downloadFile, x)));
}
function to_candid_EquipmentType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentType): _EquipmentType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_MuscleGroupCard_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuscleGroupCard): Promise<_MuscleGroupCard> {
    return await to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_MuscleGroup_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuscleGroup): _MuscleGroup {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    membershipStatus?: string;
}): {
    name: string;
    email: [] | [string];
    membershipStatus: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        membershipStatus: value.membershipStatus ? candid_some(value.membershipStatus) : candid_none()
    };
}
async function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    heroImage?: ExternalBlob;
    imageUrl: string;
}): Promise<{
    title: string;
    description: string;
    heroImage: [] | [_ExternalBlob];
    imageUrl: string;
}> {
    return {
        title: value.title,
        description: value.description,
        heroImage: value.heroImage ? candid_some(await to_candid_ExternalBlob_n53(_uploadFile, _downloadFile, value.heroImage)) : candid_none(),
        imageUrl: value.imageUrl
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentType): {
    bodyweight: null;
} | {
    cable: null;
} | {
    dumbbell: null;
} | {
    machine: null;
} {
    return value == EquipmentType.bodyweight ? {
        bodyweight: null
    } : value == EquipmentType.cable ? {
        cable: null
    } : value == EquipmentType.dumbbell ? {
        dumbbell: null
    } : value == EquipmentType.machine ? {
        machine: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuscleGroup): {
    triceps: null;
} | {
    shoulders: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    quads: null;
} | {
    hamstrings: null;
} | {
    glutes: null;
} | {
    calves: null;
} | {
    biceps: null;
} {
    return value == MuscleGroup.triceps ? {
        triceps: null
    } : value == MuscleGroup.shoulders ? {
        shoulders: null
    } : value == MuscleGroup.back ? {
        back: null
    } : value == MuscleGroup.core ? {
        core: null
    } : value == MuscleGroup.chest ? {
        chest: null
    } : value == MuscleGroup.quads ? {
        quads: null
    } : value == MuscleGroup.hamstrings ? {
        hamstrings: null
    } : value == MuscleGroup.glutes ? {
        glutes: null
    } : value == MuscleGroup.calves ? {
        calves: null
    } : value == MuscleGroup.biceps ? {
        biceps: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MuscleGroup>): Array<_MuscleGroup> {
    return value.map((x)=>to_candid_MuscleGroup_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
