/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AmazonProduct {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'affiliateLink' : string,
}
export interface BlogMedia {
  'imageUrls' : Array<string>,
  'videoUrls' : Array<string>,
}
export interface BlogPost {
  'id' : bigint,
  'media' : BlogMedia,
  'title' : string,
  'content' : string,
  'seoTitle' : string,
  'modifiedAt' : Time,
  'published' : boolean,
  'createdAt' : Time,
  'author' : string,
  'seoKeywords' : Array<string>,
  'memberOnly' : boolean,
  'seoMetaDescription' : string,
}
export interface BlogPostPreview {
  'id' : bigint,
  'title' : string,
  'seoTitle' : string,
  'createdAt' : Time,
  'author' : string,
  'memberOnly' : boolean,
  'seoMetaDescription' : string,
}
export type EquipmentType = { 'bodyweight' : null } |
  { 'cable' : null } |
  { 'dumbbell' : null } |
  { 'machine' : null };
export interface Exercise {
  'id' : bigint,
  'media' : ExerciseMedia,
  'primaryMuscle' : MuscleGroup,
  'cues' : string,
  'name' : string,
  'equipmentType' : EquipmentType,
  'description' : string,
  'isPlaceholder' : boolean,
  'videoUrl' : string,
  'secondaryMuscles' : Array<MuscleGroup>,
}
export interface ExerciseMedia {
  'imageUrls' : Array<string>,
  'videoUrls' : Array<string>,
}
export interface ExercisePreview {
  'id' : bigint,
  'primaryMuscle' : MuscleGroup,
  'name' : string,
  'imageUrl' : string,
}
export type ExternalBlob = Uint8Array;
export interface Membership {
  'principal' : Principal,
  'active' : boolean,
  'price' : bigint,
  'stripeId' : string,
}
export interface MiscConfig {
  'adminContactEmail' : string,
  'supportContactEmail' : string,
}
export type MuscleGroup = { 'triceps' : null } |
  { 'shoulders' : null } |
  { 'back' : null } |
  { 'core' : null } |
  { 'chest' : null } |
  { 'quads' : null } |
  { 'hamstrings' : null } |
  { 'glutes' : null } |
  { 'calves' : null } |
  { 'biceps' : null };
export interface MuscleGroupCard {
  'title' : string,
  'description' : string,
  'heroImage' : [] | [ExternalBlob],
  'imageUrl' : string,
}
export interface MuscleGroupDetails {
  'exerciseIds' : Array<bigint>,
  'card' : MuscleGroupCard,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
}
export interface NutritionArticle {
  'id' : bigint,
  'media' : BlogMedia,
  'title' : string,
  'content' : string,
  'published' : boolean,
  'createdAt' : Time,
  'author' : string,
  'memberOnly' : boolean,
}
export interface NutritionArticlePreview {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'author' : string,
  'memberOnly' : boolean,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'membershipStatus' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutRoutine {
  'principal' : Principal,
  'name' : string,
  'exercises' : Array<bigint>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAmazonProduct' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'addExercise' : ActorMethod<
    [
      string,
      string,
      MuscleGroup,
      Array<MuscleGroup>,
      EquipmentType,
      string,
      string,
      ExerciseMedia,
      boolean,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<
    [string, string, string, boolean, BlogMedia, string, string, Array<string>],
    undefined
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createNutritionArticle' : ActorMethod<
    [string, string, string, BlogMedia, boolean],
    undefined
  >,
  'createWorkoutRoutine' : ActorMethod<[string, Array<bigint>], undefined>,
  'deleteAmazonProduct' : ActorMethod<[bigint], undefined>,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deleteExercise' : ActorMethod<[bigint], undefined>,
  'deleteNutritionArticle' : ActorMethod<[bigint], undefined>,
  'deleteWorkoutRoutine' : ActorMethod<[string], undefined>,
  'getAllAmazonProducts' : ActorMethod<[], Array<AmazonProduct>>,
  'getAllBlogPostsAdmin' : ActorMethod<[], Array<BlogPost>>,
  'getAllExercisePreviews' : ActorMethod<[], Array<ExercisePreview>>,
  'getAllExercisesAdmin' : ActorMethod<[], Array<Exercise>>,
  'getAllMuscleGroups' : ActorMethod<[], Array<MuscleGroupDetails>>,
  'getAllNutritionArticlesAdmin' : ActorMethod<[], Array<NutritionArticle>>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWorkoutRoutines' : ActorMethod<[], Array<WorkoutRoutine>>,
  'getExercise' : ActorMethod<[bigint], [] | [Exercise]>,
  'getExercisesByMuscleGroup' : ActorMethod<[MuscleGroup], Array<Exercise>>,
  'getMembership' : ActorMethod<[Principal], [] | [Membership]>,
  'getMiscConfig' : ActorMethod<[], [] | [MiscConfig]>,
  'getMuscleGroupDetails' : ActorMethod<[string], [] | [MuscleGroupDetails]>,
  'getMyMembership' : ActorMethod<[], [] | [Membership]>,
  'getNutritionArticle' : ActorMethod<[bigint], [] | [NutritionArticle]>,
  'getPrivacyPolicy' : ActorMethod<[], string>,
  'getPublishedBlogPostPreviews' : ActorMethod<[], Array<BlogPostPreview>>,
  'getPublishedNutritionArticlePreviews' : ActorMethod<
    [],
    Array<NutritionArticlePreview>
  >,
  'getStripeConfig' : ActorMethod<[], [] | [StripeConfiguration]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWorkoutRoutines' : ActorMethod<[Principal], Array<WorkoutRoutine>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'publishBlogPost' : ActorMethod<[bigint, boolean], undefined>,
  'publishNutritionArticle' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMembership' : ActorMethod<
    [Principal, boolean, string, bigint],
    undefined
  >,
  'setMiscConfig' : ActorMethod<[MiscConfig], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAmazonProduct' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateBlogPost' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      boolean,
      BlogMedia,
      string,
      string,
      Array<string>,
    ],
    undefined
  >,
  'updateExercise' : ActorMethod<
    [
      bigint,
      string,
      string,
      MuscleGroup,
      Array<MuscleGroup>,
      EquipmentType,
      string,
      string,
      ExerciseMedia,
      boolean,
    ],
    undefined
  >,
  'updateMuscleGroupCard' : ActorMethod<[string, MuscleGroupCard], undefined>,
  'updateNutritionArticle' : ActorMethod<
    [bigint, string, string, string, BlogMedia, boolean],
    undefined
  >,
  'updateWorkoutRoutine' : ActorMethod<[string, Array<bigint>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];