/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    id: bigint;
    difficultyLevel: DifficultyLevel;
    name: string;
    equipmentType: EquipmentType;
    instructions: string;
    mediaUrl: string;
    imageUrl: string;
    benefits: string;
    muscleGroup: MuscleGroup;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    seoTitle: string;
    modifiedAt: Time;
    published: boolean;
    createdAt: Time;
    author: string;
    seoKeywords: Array<string>;
    seoMetaDescription: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MuscleGroupDetails {
    exerciseIds: Array<bigint>;
    name: string;
    description: string;
    imageUrl: string;
}
export interface Routine {
    breathworkPracticeIds: Array<bigint>;
    exerciseIds: Array<bigint>;
    userId: Principal;
}
export interface BreathworkPractice {
    id: bigint;
    difficultyLevel: DifficultyLevel;
    duration: bigint;
    name: string;
    mindfulnessBenefits: string;
    recommendedExerciseIds: Array<bigint>;
    techniqueDescription: string;
    mediaUrl: string;
}
export interface UserProfile {
    name: string;
    musicPreference: MusicPreference;
}
export enum DifficultyLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum EquipmentType {
    bodyweight = "bodyweight",
    cable = "cable",
    barbell = "barbell",
    dumbbell = "dumbbell",
    bands = "bands",
    machine = "machine"
}
export enum MuscleGroup {
    shoulders = "shoulders",
    arms = "arms",
    back = "back",
    core = "core",
    chest = "chest",
    legs = "legs"
}
export enum MusicPreference {
    on = "on",
    off = "off"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBreathworkPractice(name: string, techniqueDescription: string, mediaUrl: string, recommendedExerciseIds: Array<bigint>, mindfulnessBenefits: string, duration: bigint, difficulty: DifficultyLevel): Promise<void>;
    addExercise(name: string, muscleGroup: MuscleGroup, equipmentType: EquipmentType, difficulty: DifficultyLevel, instructions: string, mediaUrl: string, imageUrl: string, benefits: string): Promise<void>;
    addMuscleGroup(name: string, description: string, imageUrl: string): Promise<void>;
    addToRoutine(exerciseId: bigint, isBreathwork: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBlogPost(title: string, content: string, author: string, seoTitle: string, seoMetaDescription: string, seoKeywords: Array<string>): Promise<bigint>;
    createRoutine(): Promise<void>;
    deleteBlogPost(id: bigint): Promise<void>;
    deleteBreathworkPractice(breathworkPracticeId: bigint): Promise<void>;
    deleteExercise(exerciseId: bigint): Promise<void>;
    deleteMuscleGroup(name: string): Promise<void>;
    deleteRoutine(): Promise<void>;
    editBlogPost(id: bigint, title: string, content: string, author: string, seoTitle: string, seoMetaDescription: string, seoKeywords: Array<string>): Promise<void>;
    editBreathworkPractice(id: bigint, name: string, techniqueDescription: string, mediaUrl: string, recommendedExerciseIds: Array<bigint>, mindfulnessBenefits: string, duration: bigint, difficulty: DifficultyLevel): Promise<void>;
    editExercise(id: bigint, name: string, muscleGroup: MuscleGroup, equipmentType: EquipmentType, difficulty: DifficultyLevel, instructions: string, mediaUrl: string, imageUrl: string, benefits: string): Promise<void>;
    editMuscleGroup(name: string, description: string, imageUrl: string): Promise<void>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllBreathworkPractices(): Promise<Array<BreathworkPractice>>;
    getAllExercises(): Promise<Array<Exercise>>;
    getAllMuscleGroups(): Promise<Array<MuscleGroupDetails>>;
    getBlogPost(id: bigint): Promise<BlogPost | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMuscleGroupDetails(muscleGroupName: string): Promise<{
        exercises: Array<Exercise>;
        muscleGroup: MuscleGroupDetails;
    } | null>;
    getMuscleGroupExercises(muscleGroup: MuscleGroup): Promise<Array<Exercise>>;
    getRoutine(userId: Principal): Promise<Routine | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    publishBlogPost(id: bigint): Promise<void>;
    removeFromRoutine(exerciseId: bigint, isBreathwork: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unpublishBlogPost(id: bigint): Promise<void>;
    updateMusicPreference(preference: MusicPreference): Promise<void>;
}
import type { BlogPost as _BlogPost, BreathworkPractice as _BreathworkPractice, DifficultyLevel as _DifficultyLevel, EquipmentType as _EquipmentType, Exercise as _Exercise, MuscleGroup as _MuscleGroup, MuscleGroupDetails as _MuscleGroupDetails, MusicPreference as _MusicPreference, Routine as _Routine, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBreathworkPractice(arg0: string, arg1: string, arg2: string, arg3: Array<bigint>, arg4: string, arg5: bigint, arg6: DifficultyLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBreathworkPractice(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_DifficultyLevel_n8(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBreathworkPractice(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_DifficultyLevel_n8(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async addExercise(arg0: string, arg1: MuscleGroup, arg2: EquipmentType, arg3: DifficultyLevel, arg4: string, arg5: string, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExercise(arg0, to_candid_MuscleGroup_n10(this._uploadFile, this._downloadFile, arg1), to_candid_EquipmentType_n12(this._uploadFile, this._downloadFile, arg2), to_candid_DifficultyLevel_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExercise(arg0, to_candid_MuscleGroup_n10(this._uploadFile, this._downloadFile, arg1), to_candid_EquipmentType_n12(this._uploadFile, this._downloadFile, arg2), to_candid_DifficultyLevel_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addMuscleGroup(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMuscleGroup(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMuscleGroup(arg0, arg1, arg2);
            return result;
        }
    }
    async addToRoutine(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToRoutine(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToRoutine(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBlogPost(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createRoutine(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoutine();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoutine();
            return result;
        }
    }
    async deleteBlogPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteBreathworkPractice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBreathworkPractice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBreathworkPractice(arg0);
            return result;
        }
    }
    async deleteExercise(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExercise(arg0);
            return result;
        }
    }
    async deleteMuscleGroup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMuscleGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMuscleGroup(arg0);
            return result;
        }
    }
    async deleteRoutine(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoutine();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoutine();
            return result;
        }
    }
    async editBlogPost(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async editBreathworkPractice(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Array<bigint>, arg5: string, arg6: bigint, arg7: DifficultyLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editBreathworkPractice(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_DifficultyLevel_n8(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editBreathworkPractice(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_DifficultyLevel_n8(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async editExercise(arg0: bigint, arg1: string, arg2: MuscleGroup, arg3: EquipmentType, arg4: DifficultyLevel, arg5: string, arg6: string, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editExercise(arg0, arg1, to_candid_MuscleGroup_n10(this._uploadFile, this._downloadFile, arg2), to_candid_EquipmentType_n12(this._uploadFile, this._downloadFile, arg3), to_candid_DifficultyLevel_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editExercise(arg0, arg1, to_candid_MuscleGroup_n10(this._uploadFile, this._downloadFile, arg2), to_candid_EquipmentType_n12(this._uploadFile, this._downloadFile, arg3), to_candid_DifficultyLevel_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async editMuscleGroup(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editMuscleGroup(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMuscleGroup(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return result;
        }
    }
    async getAllBreathworkPractices(): Promise<Array<BreathworkPractice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBreathworkPractices();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBreathworkPractices();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercises();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercises();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMuscleGroups(): Promise<Array<MuscleGroupDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMuscleGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMuscleGroups();
            return result;
        }
    }
    async getBlogPost(arg0: bigint): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMuscleGroupDetails(arg0: string): Promise<{
        exercises: Array<Exercise>;
        muscleGroup: MuscleGroupDetails;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMuscleGroupDetails(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMuscleGroupDetails(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMuscleGroupExercises(arg0: MuscleGroup): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMuscleGroupExercises(to_candid_MuscleGroup_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMuscleGroupExercises(to_candid_MuscleGroup_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoutine(arg0: Principal): Promise<Routine | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutine(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutine(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publishBlogPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishBlogPost(arg0);
            return result;
        }
    }
    async removeFromRoutine(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromRoutine(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromRoutine(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unpublishBlogPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishBlogPost(arg0);
            return result;
        }
    }
    async updateMusicPreference(arg0: MusicPreference): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMusicPreference(to_candid_MusicPreference_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMusicPreference(to_candid_MusicPreference_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BreathworkPractice_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BreathworkPractice): BreathworkPractice {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_DifficultyLevel_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DifficultyLevel): DifficultyLevel {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_EquipmentType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EquipmentType): EquipmentType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Exercise_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_MuscleGroup_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MuscleGroup): MuscleGroup {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_MusicPreference_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MusicPreference): MusicPreference {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        exercises: Array<_Exercise>;
        muscleGroup: _MuscleGroupDetails;
    }]): {
    exercises: Array<Exercise>;
    muscleGroup: MuscleGroupDetails;
} | null {
    return value.length === 0 ? null : from_candid_record_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Routine]): Routine | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficultyLevel: _DifficultyLevel;
    duration: bigint;
    name: string;
    mindfulnessBenefits: string;
    recommendedExerciseIds: Array<bigint>;
    techniqueDescription: string;
    mediaUrl: string;
}): {
    id: bigint;
    difficultyLevel: DifficultyLevel;
    duration: bigint;
    name: string;
    mindfulnessBenefits: string;
    recommendedExerciseIds: Array<bigint>;
    techniqueDescription: string;
    mediaUrl: string;
} {
    return {
        id: value.id,
        difficultyLevel: from_candid_DifficultyLevel_n19(_uploadFile, _downloadFile, value.difficultyLevel),
        duration: value.duration,
        name: value.name,
        mindfulnessBenefits: value.mindfulnessBenefits,
        recommendedExerciseIds: value.recommendedExerciseIds,
        techniqueDescription: value.techniqueDescription,
        mediaUrl: value.mediaUrl
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficultyLevel: _DifficultyLevel;
    name: string;
    equipmentType: _EquipmentType;
    instructions: string;
    mediaUrl: string;
    imageUrl: string;
    benefits: string;
    muscleGroup: _MuscleGroup;
}): {
    id: bigint;
    difficultyLevel: DifficultyLevel;
    name: string;
    equipmentType: EquipmentType;
    instructions: string;
    mediaUrl: string;
    imageUrl: string;
    benefits: string;
    muscleGroup: MuscleGroup;
} {
    return {
        id: value.id,
        difficultyLevel: from_candid_DifficultyLevel_n19(_uploadFile, _downloadFile, value.difficultyLevel),
        name: value.name,
        equipmentType: from_candid_EquipmentType_n24(_uploadFile, _downloadFile, value.equipmentType),
        instructions: value.instructions,
        mediaUrl: value.mediaUrl,
        imageUrl: value.imageUrl,
        benefits: value.benefits,
        muscleGroup: from_candid_MuscleGroup_n26(_uploadFile, _downloadFile, value.muscleGroup)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    musicPreference: _MusicPreference;
}): {
    name: string;
    musicPreference: MusicPreference;
} {
    return {
        name: value.name,
        musicPreference: from_candid_MusicPreference_n32(_uploadFile, _downloadFile, value.musicPreference)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exercises: Array<_Exercise>;
    muscleGroup: _MuscleGroupDetails;
}): {
    exercises: Array<Exercise>;
    muscleGroup: MuscleGroupDetails;
} {
    return {
        exercises: from_candid_vec_n21(_uploadFile, _downloadFile, value.exercises),
        muscleGroup: value.muscleGroup
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): DifficultyLevel {
    return "intermediate" in value ? DifficultyLevel.intermediate : "beginner" in value ? DifficultyLevel.beginner : "advanced" in value ? DifficultyLevel.advanced : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bodyweight: null;
} | {
    cable: null;
} | {
    barbell: null;
} | {
    dumbbell: null;
} | {
    bands: null;
} | {
    machine: null;
}): EquipmentType {
    return "bodyweight" in value ? EquipmentType.bodyweight : "cable" in value ? EquipmentType.cable : "barbell" in value ? EquipmentType.barbell : "dumbbell" in value ? EquipmentType.dumbbell : "bands" in value ? EquipmentType.bands : "machine" in value ? EquipmentType.machine : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shoulders: null;
} | {
    arms: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    legs: null;
}): MuscleGroup {
    return "shoulders" in value ? MuscleGroup.shoulders : "arms" in value ? MuscleGroup.arms : "back" in value ? MuscleGroup.back : "core" in value ? MuscleGroup.core : "chest" in value ? MuscleGroup.chest : "legs" in value ? MuscleGroup.legs : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    on: null;
} | {
    off: null;
}): MusicPreference {
    return "on" in value ? MusicPreference.on : "off" in value ? MusicPreference.off : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BreathworkPractice>): Array<BreathworkPractice> {
    return value.map((x)=>from_candid_BreathworkPractice_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n22(_uploadFile, _downloadFile, x));
}
function to_candid_DifficultyLevel_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): _DifficultyLevel {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_EquipmentType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentType): _EquipmentType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_MuscleGroup_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuscleGroup): _MuscleGroup {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_MusicPreference_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MusicPreference): _MusicPreference {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    musicPreference: MusicPreference;
}): {
    name: string;
    musicPreference: _MusicPreference;
} {
    return {
        name: value.name,
        musicPreference: to_candid_MusicPreference_n41(_uploadFile, _downloadFile, value.musicPreference)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MuscleGroup): {
    shoulders: null;
} | {
    arms: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    legs: null;
} {
    return value == MuscleGroup.shoulders ? {
        shoulders: null
    } : value == MuscleGroup.arms ? {
        arms: null
    } : value == MuscleGroup.back ? {
        back: null
    } : value == MuscleGroup.core ? {
        core: null
    } : value == MuscleGroup.chest ? {
        chest: null
    } : value == MuscleGroup.legs ? {
        legs: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentType): {
    bodyweight: null;
} | {
    cable: null;
} | {
    barbell: null;
} | {
    dumbbell: null;
} | {
    bands: null;
} | {
    machine: null;
} {
    return value == EquipmentType.bodyweight ? {
        bodyweight: null
    } : value == EquipmentType.cable ? {
        cable: null
    } : value == EquipmentType.barbell ? {
        barbell: null
    } : value == EquipmentType.dumbbell ? {
        dumbbell: null
    } : value == EquipmentType.bands ? {
        bands: null
    } : value == EquipmentType.machine ? {
        machine: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MusicPreference): {
    on: null;
} | {
    off: null;
} {
    return value == MusicPreference.on ? {
        on: null
    } : value == MusicPreference.off ? {
        off: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DifficultyLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == DifficultyLevel.intermediate ? {
        intermediate: null
    } : value == DifficultyLevel.beginner ? {
        beginner: null
    } : value == DifficultyLevel.advanced ? {
        advanced: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
